### ISSUE TITLE
如果不区分两种布局，只是单独的显示图片，怎么搞？

### ISSUE THREAD

**Issue by ghost** [gjiazhe/LayoutSwitch#1]

**Comment by gjiazhe** [comment]
抱歉这么晚回复。
您指的是不改变 item 的布局只改变 item 的列数吗？
当 item 列数改变时，RecyclerView 会重新计算每个 item 的宽度的。你可以试试改变 GridLayoutManager 的 setSpanCount(int count) 接口中 count 的数值，看看效果。
